[2024-07-25T12:18:05.935+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T12:18:05.947+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.update_dds_data manual__2024-07-25T12:12:44.651024+00:00 [queued]>
[2024-07-25T12:18:05.950+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.update_dds_data manual__2024-07-25T12:12:44.651024+00:00 [queued]>
[2024-07-25T12:18:05.950+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-25T12:18:05.956+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): update_dds_data> on 2024-07-25 12:12:44.651024+00:00
[2024-07-25T12:18:05.961+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=190) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T12:18:05.962+0000] {standard_task_runner.py:63} INFO - Started process 192 to run task
[2024-07-25T12:18:05.962+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'update_dds_data', 'manual__2024-07-25T12:12:44.651024+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmphvqs6r4z']
[2024-07-25T12:18:05.964+0000] {standard_task_runner.py:91} INFO - Job 382: Subtask update_dds_data
[2024-07-25T12:18:05.983+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.update_dds_data manual__2024-07-25T12:12:44.651024+00:00 [running]> on host ce8b503e836d
[2024-07-25T12:18:06.000+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'update_dds_data', field 'sql'. Template: '/opt/***/dags/scripts/sql-scripts/dds_refresh.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/scripts/sql-scripts/dds_refresh.sql
[2024-07-25T12:18:06.001+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/dags/scripts/sql-scripts/dds_refresh.sql
[2024-07-25T12:18:06.005+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=update_dds_data, run_id=manual__2024-07-25T12:12:44.651024+00:00, execution_date=20240725T121244, start_date=20240725T121805, end_date=20240725T121806
[2024-07-25T12:18:06.009+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 382 for task update_dds_data (/opt/airflow/dags/scripts/sql-scripts/dds_refresh.sql; 192)
[2024-07-25T12:18:06.021+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-25T12:18:06.024+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-07-25T12:18:06.029+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T12:18:06.030+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
