[2024-07-12T22:28:25.811+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T22:28:25.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-12T22:28:18.276619+00:00 [queued]>
[2024-07-12T22:28:25.823+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-12T22:28:18.276619+00:00 [queued]>
[2024-07-12T22:28:25.824+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-12T22:28:25.829+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_dump> on 2024-07-12 22:28:18.276619+00:00
[2024-07-12T22:28:25.833+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=999) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T22:28:25.834+0000] {standard_task_runner.py:63} INFO - Started process 1001 to run task
[2024-07-12T22:28:25.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'create_dump', 'manual__2024-07-12T22:28:18.276619+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmp6v9omgzf']
[2024-07-12T22:28:25.836+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask create_dump
[2024-07-12T22:28:25.873+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.create_dump manual__2024-07-12T22:28:18.276619+00:00 [running]> on host 861c3600257c
[2024-07-12T22:28:25.954+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T22:28:18.276619+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T22:28:18.276619+00:00'
[2024-07-12T22:28:25.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T22:28:25.982+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T22:28:25.984+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/init_ods.py", line 41, in create_dump
    dump_schema_and_data(
    ^^^^^^^^^^^^^^^^^^^^
NameError: name 'dump_schema_and_data' is not defined
[2024-07-12T22:28:25.996+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=init_ods_layer, task_id=create_dump, run_id=manual__2024-07-12T22:28:18.276619+00:00, execution_date=20240712T222818, start_date=20240712T222825, end_date=20240712T222825
[2024-07-12T22:28:26.013+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task create_dump (name 'dump_schema_and_data' is not defined; 1001)
[2024-07-12T22:28:26.055+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-12T22:28:26.087+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-12T22:28:26.090+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
