[2024-07-12T22:40:02.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-12T22:40:02.885+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-12T22:39:57.735535+00:00 [queued]>
[2024-07-12T22:40:02.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_ods_layer.create_dump manual__2024-07-12T22:39:57.735535+00:00 [queued]>
[2024-07-12T22:40:02.888+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-12T22:40:02.894+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_dump> on 2024-07-12 22:39:57.735535+00:00
[2024-07-12T22:40:02.899+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-12T22:40:02.900+0000] {standard_task_runner.py:63} INFO - Started process 1157 to run task
[2024-07-12T22:40:02.900+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_ods_layer', 'create_dump', 'manual__2024-07-12T22:39:57.735535+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/init_ods.py', '--cfg-path', '/tmp/tmp12zlo1g4']
[2024-07-12T22:40:02.902+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask create_dump
[2024-07-12T22:40:02.924+0000] {task_command.py:426} INFO - Running <TaskInstance: init_ods_layer.create_dump manual__2024-07-12T22:39:57.735535+00:00 [running]> on host 861c3600257c
[2024-07-12T22:40:02.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_ods_layer' AIRFLOW_CTX_TASK_ID='create_dump' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T22:39:57.735535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T22:39:57.735535+00:00'
[2024-07-12T22:40:02.961+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-12T22:40:05.033+0000] {logging_mixin.py:188} INFO - Ошибка при экспорте схемы и данных: Command '['pg_dump', '-U', 'etl_user_3', '-h', '10.82.0.4', '-n', 'source_data', '-f', 'scripts/sql-scripts/ods_migration.sql', 'source']' returned non-zero exit status 1.
[2024-07-12T22:40:05.043+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-12T22:40:05.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-12T22:40:05.117+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=init_ods_layer, task_id=create_dump, run_id=manual__2024-07-12T22:39:57.735535+00:00, execution_date=20240712T223957, start_date=20240712T224002, end_date=20240712T224005
[2024-07-12T22:40:05.161+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-12T22:40:05.210+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-12T22:40:05.212+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
